/**
 * Shared help text for /cdev and /cdev-help.
 *
 * Kept in its own module so it can be tested and imported without pulling in
 * the peer dependencies required by the full command handler.
 */

export const CDEV_SUBCOMMAND_HELP = [
  "──────────────────────────────────────",
  "/cdev <task>           Scout + Forge explore",
  "/cdev quick <task>     Scout only (fast)",
  "/cdev fast <task>      Alias for quick (scout only)",
  "/cdev verify <task>    Scout ×2 + forge (higher accuracy)",
  "/cdev research <issue> Agent-driven investigation, no edits",
  "/cdev advisor <question> Scout + advisor recommendation (when stuck)",
  "/cdev ask-advisor <question> Ask advisor directly (no scout)",
  "/cdev multi <n> [backup|no-backup] <task>  Split scout into N scouts (requires map)",
  "/cdev plan <task>      Scout + planner (implementation plan only)",
  "/cdev yolo <task>      Scout + forge, then review loops",
  "/cdev yolo manual|propose|auto  Who applies fixes (auto = cdev edits files)",
  "/cdev review [path]    Forge review session/file",
  "/cdev review changes   Review uncommitted changes",
  "/cdev review A..B      Review git/svn diff",
  "/cdev scan [deep]      Generate custom prompts",
  "/cdev map              Generate project map",
  "/cdev map refresh      Regenerate project map via scout+forge",
  "/cdev map show         View project map",
  "/cdev history [n]      Past session details",
  "/cdev recall [topic]   Check project memory",
  "/cdev memory refresh <topic>  Re-explore stale topic",
  "/cdev memory auto-refresh on|off  Auto-refresh stale topics on recall",
  "/cdev replay <n>       Re-run a past session",
  "/cdev status           Config overview",
  "/cdev config           Show/edit settings",
  "/cdev config <key> <value>",
  "/cdev config project <key> <value>",
  "/cdev retry            Retry last cdev session",
  "/cdev estimate <task>  Preview cost/tokens",
  "/cdev memory on|off    Toggle project memory",
  "/cdev prompts on|off   Toggle custom prompts",
  "/cdev themed on|off    Toggle themed TUI",
  "/cdev auto on|off      Toggle auto-trigger",
  "/cdev auto-verify on|off  Toggle automatic scout ×2",
  "/cdev auto-compact on|off Toggle auto-compact near model limit",
  "/cdev yolo on|off      Toggle YOLO review loops",
  "/cdev yolo manual|propose|auto  Who applies fixes (auto = cdev edits files)",
  "/cdev clear            Clear memory + reports",
  "/cdev clear error      Clear error log",
  "/cdev clear reports    Clear old reports",
  "──────────────────────────────────────",
  "/cdev-model            Pick scout/forge models",
  "/cdev-help             This help",
];
